apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: demo-loan-rfc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: mlserver-0.x
      storageUri: "https://github.com/RobGeada/trustyai_april12_demo_model/blob/main/loan_model.sav?raw=true"