apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: demo-loan-nn-alpha-onnx
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      runtime: ovms-1.x
      storageUri: "https://github.com/RobGeada/trustyai_april12_demo/blob/main/resources/loan_model_alpha.onnx?raw=true"